### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by kadistudio** [kravetsone/enkaNetwork#3]
i noticed that when fetching a user (especially using a begineers namecard (Genshin Impact: A New World) an error occurs (see attached picture).

const userEnka = await enka.fetchUser(uid);

how long does the module update? because when i change something information in the game, when i try to console.log(userEnka) there's nothing change with the information.

![image](https://user-images.githubusercontent.com/70886239/200443336-e4634162-64c2-41f4-8756-e90a9f89d436.png)

**Comment by kravetsone** [comment]
> how long does the module update? because when i change something information in the game, when i try to console.log(userEnka) there's nothing change with the information.

On the part of the **`enka network API`**, the response is cached and updated every `2 minutes`. Caching by the library is calculated just from the life of the `enka network api cache`.

Sorry. I'm coming back from college and will be able to investigate the error a little later.

**Comment by kravetsone** [comment]
# Fixed in [enkaNetwork@1.1.5](https://github.com/kravetsone/enkaNetwork/releases/tag/enkaNetwork%401.1.5)
### Thank you for your cooperation! At the moment dummy accounts do not cause errors but contain a lot of undefined values. (as it should have been)
![image](https://user-images.githubusercontent.com/57632712/200604080-f1f6401b-c304-487b-bdc8-5d1bcb62f5bd.png)
