### ISSUE TITLE
Refused to set unsafe header "User-Agent"

### ISSUE THREAD

**Issue by erisvn** [kravetsone/enkaNetwork#4]
![image](https://user-images.githubusercontent.com/69683870/201113840-0d9048a8-7a0d-4553-898a-6bb2821b561b.png)

**Comment by kravetsone** [comment]
# Fixed in [enkaNetwork@1.1.6](https://github.com/kravetsone/enkaNetwork/releases/tag/enkaNetwork%401.1.6)
### Thank you for your cooperation! I investigated your problem and fixed it. Please check if it helped you or not.
For intsall new version you can use: `npm i enkaNetwork@latest`
and set the value of `userAgent` key to `false`. This should help you.
```js
const enka = new EnkaNetwork({ userAgent: false });
```

**Comment by erisvn** [comment]
tysm
